export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as ArtistRegister } from './ArtistRegister'
export { default as AddSong } from './AddSong'
export { default as Profile } from './Profile'